### ISSUE TITLE
Error on clean_headr

### ISSUE THREAD

**Issue by scamicha** [mattroumaya/doubleheadr#1]
I've been trying to use this package following the demo at https://www.mattroumaya.com/post/doubleheadr-surveymonkey-column-cleaning-in-r/, but I keep getting this error.

`> demo %>% clean_headr(., "...", clean_names = TRUE) %>% colnames(.)` 
`Error in startsWith(name, rep_val) : non-character object(s)`

**Comment by mattroumaya** [comment]
Any way you can provide a sample of your data or the column names? I'll be happy to try and troubleshoot but am unsure what's causing that error.

**Comment by scamicha** [comment]
I was using the frame doubleheadr::demo. However, I upgraded R from 3.6.3 to 4.2 last night and it is working now. Sorry for the false alarm!

**Comment by mattroumaya** [comment]
Cool - no problem at all! Hope it's working out for you!
